spring:
  profiles:
    default: development
    active: development 
  jackson.deserialization.fail-on-unknown-properties: true 


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: "${hystrixThreadTimeoutInMillis}"
          strategy: SEMAPHORE
      fallback:
        enabled: "${fallbackEnabled}"
      circuitBreaker:
        enabled: "${circuitEnabled}"
        sleepWindowInMilliseconds: "${sleepWindowInMilliseconds}"
        requestVolumeThreshold: "${requestVolumeThreshold}"

---

spring:
  profiles: development
  
# context Path
server:
    port: 9080   
       
---

spring:
  profiles: test
  
# context Path
server:
    port: 9080

---

spring:
  profiles: production
  
# context Path
server:
    port: 9080

---
# common properties for yaml 

# context Path
server:
  servlet:
    context-path: ${context-root}${app-version}
